import { EnrichedTrack } from "./types";

/**
 * Mock tracks using the same test data from the main project.
 * Artwork images are bundled in public/images/test-artwork/.
 */
export const MOCK_TRACKS: EnrichedTrack[] = [
  {
    id: "test-001",
    artist: "Deadmau5",
    title: "Strobe",
    label: "Mau5trap",
    genre: "Progressive House",
    bpm: 128,
    key: "F#m",
    artworkUrl: "/images/test-artwork/strobe.jpg",
    signature: "deadmau5|strobe",
    source: "mock",
    timestamp: new Date().toISOString(),
    enrichedAt: new Date().toISOString(),
  },
  {
    id: "test-002",
    artist: "Eric Prydz",
    title: "Opus",
    label: "Pryda",
    genre: "Progressive House",
    bpm: 126,
    key: "Dm",
    artworkUrl: "/images/test-artwork/opus.jpg",
    signature: "eric-prydz|opus",
    source: "mock",
    timestamp: new Date().toISOString(),
    enrichedAt: new Date().toISOString(),
  },
  {
    id: "test-003",
    artist: "Above & Beyond",
    title: "Sun & Moon",
    label: "Anjunabeats",
    genre: "Trance",
    bpm: 134,
    key: "Eb",
    artworkUrl: "/images/test-artwork/sun-and-moon.jpg",
    signature: "above-and-beyond|sun-and-moon",
    source: "mock",
    timestamp: new Date().toISOString(),
    enrichedAt: new Date().toISOString(),
  },
  {
    id: "test-004",
    artist: "Daft Punk",
    title: "One More Time",
    label: "Virgin",
    genre: "French House",
    bpm: 122,
    key: "Bbm",
    artworkUrl: "/images/test-artwork/one-more-time.jpg",
    signature: "daft-punk|one-more-time",
    source: "mock",
    timestamp: new Date().toISOString(),
    enrichedAt: new Date().toISOString(),
  },
  {
    id: "test-005",
    artist: "Swedish House Mafia",
    title: "Don't You Worry Child",
    label: "Virgin EMI",
    genre: "Progressive House",
    bpm: 129,
    key: "G",
    artworkUrl: "/images/test-artwork/dont-you-worry-child.jpg",
    signature: "swedish-house-mafia|dont-you-worry-child",
    source: "mock",
    timestamp: new Date().toISOString(),
    enrichedAt: new Date().toISOString(),
  },
];
